### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""

### ISSUE THREAD

**Issue by TemporalAgent7** [nodegui/react-nodegui-starter#1]
While running `npm start` I'm seeing this output:

```
C:\react-nodegui-starter>npm start

> react-nodegui-starter@1.0.0 start C:\react-nodegui-starter
> tsc && qode ./dist/index.js

qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

This is a pretty standard Windows 10 machine. Let me know what other diagnostics / logs I can collect.

**Comment by a7ul** [comment]
Thanks for pointing this out! Seems like the issue was that I had Qt installed on my system already so Qt was able to automagically find the platform files needed. 

I will fix this for systems that dont have qt installed. :)

**Comment by a7ul** [comment]
This is solved in the latest release of nodegui.

Just take a pull on this repo and do npm install and npm start and it should just work!
Closing this issue. Reopen if it persists :)

**Comment by Naahuel** [comment]
I have the latest version of this repo installed and I have the same problem.

**Environment:**
```
OS: Pop!_OS 19.04 x86_64
node: v12.8.1
npm: 6.10.2
gcc: gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)
```

`npm install` installs fine, but running `npm start` shows:

```
> react-nodegui-starter@1.0.0 start /home/nahuel/Projects/react-nodegui-starter
> tsc && qode ./dist/index.js

qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

If I run it like this: `QT_DEBUG_PLUGINS=1 npm start` it shows a little bit more of information:
```
> react-nodegui-starter@1.0.0 start /home/nahuel/Projects/react-nodegui-starter
> tsc && qode ./dist/index.js

QFactoryLoader::QFactoryLoader() checking directory path "/home/nahuel/Projects/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.2/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by a7ul** [comment]
Hey @Naahuel  
I just fixed the linux version of the release.
 Could you 
rm -rf your node_modules 
rm -rf ~/.cache/qode*

And then do a 
npm install
npm start

**Comment by Naahuel** [comment]
Brilliant! it works! :D

**Comment by a7ul** [comment]
Wohoo!! Finallyy!
Awesome!

**Comment by a7ul** [comment]
Thanks for helping me debug the issue @Naahuel  Cheers 🍺

**Comment by Naahuel** [comment]
Thank **you**! This is a great idea and I hope it succeeds!
