### ISSUE TITLE
Unexpected token \u0000 on npm install 

### ISSUE THREAD

**Issue by dubeyAditya** [nodegui/react-nodegui-starter#10]
![image](https://user-images.githubusercontent.com/23243469/64061303-bb859d00-cbf6-11e9-949b-d22622c576ac.png)

**Comment by a7ul** [comment]
This is very strange @dubeyAditya 
Seems like progress npm module is breaking because of an invalid unicode character 😓 

Have you tried doing npm install in powershell ?

**Comment by a7ul** [comment]
Also, could you try this aswell and report back ? https://stackoverflow.com/a/31635673/2881112

**Comment by dubeyAditya** [comment]
It's in Powershell only Node version is 8+ but ideally it is strange for me too.

**Comment by a7ul** [comment]
Can you make sure you have setup the environment like stated here: https://nodegui.github.io/nodegui/#/tutorial/development-environment?id=setting-up-windows ?
Node v8 is not supported actually.

**Comment by dubeyAditya** [comment]
Thanks Atul for your help. I will try it. Currently it is working for me on Linux.
Some of Problem I Observed here :
1. No Html support
2. No Css Library Support
3. No React Component Supported.
4. Existing Component like Button wont accepts class Name
5. Document is not Intuitive to getting started
