### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by abhigk** [nodegui/react-nodegui-starter#126]
I have downloaded the starter template. However, it is giving me error in during npm install.

![Screen Shot 2020-04-15 at 9 15 16 pm](https://user-images.githubusercontent.com/9884510/79331336-56e93980-7f5e-11ea-81e2-2231ae510c84.png)

Here is the debug log

[2020-04-15T11_02_18_500Z-debug.log](https://github.com/nodegui/react-nodegui-starter/files/4480855/2020-04-15T11_02_18_500Z-debug.log)

**Comment by a7ul** [comment]
Hi @abhigk Could you post the complete log ?
This is just prebuilt failing, the actual error log should be after this.

**Comment by abhigk** [comment]
Now it working for some reason on the second try. However, there still error on prebuild install. I have attached all the screenshots. Let me know for any help.
![Screen Shot 2020-04-15 at 9 38 05 pm](https://user-images.githubusercontent.com/9884510/79333405-d2001f00-7f61-11ea-9313-fb6178917475.png)
![Screen Shot 2020-04-15 at 9 38 18 pm](https://user-images.githubusercontent.com/9884510/79333412-d4627900-7f61-11ea-883c-121132839000.png)
![Screen Shot 2020-04-15 at 9 38 26 pm](https://user-images.githubusercontent.com/9884510/79333422-d9bfc380-7f61-11ea-869f-29b59e6e9e7a.png)

![Screen Shot 2020-04-15 at 9 38 40 pm](https://user-images.githubusercontent.com/9884510/79333432-ddebe100-7f61-11ea-810f-a39337069944.png)

![Screen Shot 2020-04-15 at 9 38 44 pm](https://user-images.githubusercontent.com/9884510/79333442-e2b09500-7f61-11ea-8446-c138c3b523f2.png)

**Comment by a7ul** [comment]
The prebuilt error is expected since we have disabled prebuilt binaries for now due to few bugs. But it should work as expected.
