### ISSUE TITLE
Update docs to fix running the app

### ISSUE THREAD

**Issue by praisethemoon** [nodegui/react-nodegui-starter#19]
Hello!

 I came from the docs here [https://react.nodegui.org/docs/guides/getting-started#hello-world](https://react.nodegui.org/docs/guides/getting-started#hello-world)

Which says to run `npm install` and then `npm start` after clonign the repo, which does not work, as the readme here asks to run `npm run dev` instead.

I think updating the docs would be a good idea, cheers!

**Comment by praisethemoon** [comment]
Oh, turns out `npm start` also works, but only after running `npm run dev`, at least for me. Feel free to close the issue if I am wrong.

**Comment by a7ul** [comment]
No you are right @praisethemoon 
I had updated the started few hours ago and forgot to update the docs. Thanks for pointing out :) 

Make sure you run both npm run dev and npm start on seperate terminal tabs or windows.
