### ISSUE TITLE
Can't install, gyp/MSB error MSB8020: The build tools for v141 cannot be found.

### ISSUE THREAD

**Issue by cjones1313** [nodegui/react-nodegui-starter#8]
I'm running into this issue during 'npm install' but I have VS2017 installed. I also verified that the correct components are installed. Any ideas?

Not sure if this makes a difference but I also have VS2010 and VS2015 installed.

![image](https://user-images.githubusercontent.com/54443993/63598356-62ca5a80-c58d-11e9-9e85-4aee036989b2.png)

image
![image](https://user-images.githubusercontent.com/54443993/63598089-e0da3180-c58c-11e9-8618-4759d5eebd03.png)

**Comment by a7ul** [comment]
You should install the c++ for desktop environment in "Workload section"

**Comment by cjones1313** [comment]
I already have and use it often. From Visual Studio Installer -> Modify: 
![image](https://user-images.githubusercontent.com/54443993/63608069-0c1b4b80-c5a2-11e9-8df1-ce1015726d9f.png)

**Comment by a7ul** [comment]
Maybe this can help https://stackoverflow.com/a/50673771/2881112

@cjones1313

**Comment by cjones1313** [comment]
Thank you @master-atul. It required running "npm i" twice as one of the responses in your link suggested but the main problem for me were VS env vars set to 2015 (version 14). This was my fault and I should have remembered I have things configured to use the 2015 compiler by default. 

Running this batch file in the command window before 'npm i' resolved it: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat. 

Thanks.
