### ISSUE TITLE
Packaging the App

### ISSUE THREAD

**Issue by madhavarshney** [nodegui/react-nodegui-starter#83]
Hello! I was able to successfully run the app based on the instructions. I also used `@nodegui/packer` to create a bundle (on macOS for now). I think it will be useful to add the templates for app bundles in this repo and/or add information about generating them. Thanks!

**Comment by a7ul** [comment]
Hi @madhavarshney  I am not sure what you mean exactly by templates ? Could you explain it a bit.

**Comment by madhavarshney** [comment]
@master-atul I meant the folder "deploy" that is generated from running `@nodgui/packer init`. I was saying that it may be a good idea to add [these instructions](https://github.com/nodegui/packer#usage) in this repo so it is easier for people to find out how to bundle the application.

**Comment by a7ul** [comment]
Closing this issue. since the instructions are now present in starter repos.
